// Generated by text_to_data_js.py
// Raw rows parsed: 5388 | Skipped: 0 | Groups: 460
const rawDataLastUpdatedIso = "2026-05-06T14:39:09.006592Z";
const rawData = [
  {
    "from": "Ares",
    "source": "Level 25 Crypt",
    "chestNumber": 168
  },
  {
    "from": "Marauders",
    "source": "Rise of the Ancients event",
    "chestNumber": 4
  },
  {
    "from": "Karl Killer",
    "source": "Level 30 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "Marauders",
    "source": "Level 30 epic Crypt",
    "chestNumber": 9
  },
  {
    "from": "poops",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Boadicee",
    "source": "Level 25 Crypt",
    "chestNumber": 29
  },
  {
    "from": "Rob",
    "source": "Level 25 Crypt",
    "chestNumber": 130
  },
  {
    "from": "Darrinel",
    "source": "Level 25 Crypt",
    "chestNumber": 16
  },
  {
    "from": "MII Mighty Micho",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Matija Gubec",
    "source": "Level 25 Crypt",
    "chestNumber": 13
  },
  {
    "from": "Grimsborith Orik",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Morana",
    "source": "Level 30 epic Crypt",
    "chestNumber": 32
  },
  {
    "from": "Rob",
    "source": "Level 30 rare Crypt",
    "chestNumber": 18
  },
  {
    "from": "SmokinLauren?",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "GAGARIN",
    "source": "Level 25 Crypt",
    "chestNumber": 54
  },
  {
    "from": "Athena",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Rasses74",
    "source": "Level 25 Crypt",
    "chestNumber": 105
  },
  {
    "from": "MII Mighty Micho",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Matija Gubec",
    "source": "Level 30 rare Crypt",
    "chestNumber": 29
  },
  {
    "from": "Falcon Eye",
    "source": "Level 25 Crypt",
    "chestNumber": 25
  },
  {
    "from": "Rasses74",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Badur",
    "source": "Level 25 Crypt",
    "chestNumber": 37
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 25 Crypt",
    "chestNumber": 55
  },
  {
    "from": "Blue Lion",
    "source": "Level 25 Crypt",
    "chestNumber": 6
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 Crypt",
    "chestNumber": 51
  },
  {
    "from": "Tygojind",
    "source": "Level 25 Crypt",
    "chestNumber": 31
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 25 epic Crypt",
    "chestNumber": 12
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Darrinel",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Auth",
    "source": "Level 25 rare Crypt",
    "chestNumber": 38
  },
  {
    "from": "Marond",
    "source": "Level 25 Crypt",
    "chestNumber": 9
  },
  {
    "from": "wil",
    "source": "Level 25 Crypt",
    "chestNumber": 38
  },
  {
    "from": "zippy",
    "source": "Level 25 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 25 Crypt",
    "chestNumber": 62
  },
  {
    "from": "Marond",
    "source": "Level 30 rare Crypt",
    "chestNumber": 10
  },
  {
    "from": "Marond",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 Crypt",
    "chestNumber": 57
  },
  {
    "from": "Rob",
    "source": "Level 35 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "zippy",
    "source": "Level 25 Crypt",
    "chestNumber": 13
  },
  {
    "from": "Marauders",
    "source": "Level 25 Crypt",
    "chestNumber": 22
  },
  {
    "from": "Matija Gubec",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Karl Killer",
    "source": "Level 30 epic Crypt",
    "chestNumber": 11
  },
  {
    "from": "zippy",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Bardin",
    "source": "Level 25 Crypt",
    "chestNumber": 56
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Brakus",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 25 Crypt",
    "chestNumber": 61
  },
  {
    "from": "Sir Dori",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "GAGARIN",
    "source": "Level 25 epic Crypt",
    "chestNumber": 18
  },
  {
    "from": "Gardashura",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Brakus",
    "source": "Level 25 Crypt",
    "chestNumber": 45
  },
  {
    "from": "Sashott",
    "source": "Epic Inferno squad",
    "chestNumber": 13
  },
  {
    "from": "Kizil Elma",
    "source": "Level 25 Crypt",
    "chestNumber": 77
  },
  {
    "from": "Grande Inverno",
    "source": "Level 25 Crypt",
    "chestNumber": 45
  },
  {
    "from": "Amginad",
    "source": "Level 25 Crypt",
    "chestNumber": 29
  },
  {
    "from": "Auth",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kizil Elma",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Auth",
    "source": "Level 25 epic Crypt",
    "chestNumber": 17
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Amginad",
    "source": "Level 25 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 25 Crypt",
    "chestNumber": 81
  },
  {
    "from": "Athena",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 30 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "GAGARIN",
    "source": "Epic Inferno squad",
    "chestNumber": 4
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 30 Citadel",
    "chestNumber": 6
  },
  {
    "from": "Brakus",
    "source": "Clan wealth",
    "chestNumber": 15
  },
  {
    "from": "Athena",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Marauders",
    "source": "Union of Triumph personal reward",
    "chestNumber": 8
  },
  {
    "from": "Brakus",
    "source": "Level 25 epic Crypt",
    "chestNumber": 28
  },
  {
    "from": "Fallegin",
    "source": "Level 25 Crypt",
    "chestNumber": 37
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 25 epic Crypt",
    "chestNumber": 9
  },
  {
    "from": "Keleve",
    "source": "Epic Inferno squad",
    "chestNumber": 7
  },
  {
    "from": "Brakus",
    "source": "Level 30 rare Crypt",
    "chestNumber": 16
  },
  {
    "from": "Fankayel",
    "source": "Level 25 Crypt",
    "chestNumber": 47
  },
  {
    "from": "Kizil Elma",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kizil Elma",
    "source": "Level 25 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Kizil Elma",
    "source": "Level 25 rare Crypt",
    "chestNumber": 8
  },
  {
    "from": "Mag junior",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Bardin",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "WODORY",
    "source": "Epic Inferno squad",
    "chestNumber": 4
  },
  {
    "from": "Morana",
    "source": "Level 30 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "Ilvenen",
    "source": "Level 25 Crypt",
    "chestNumber": 19
  },
  {
    "from": "Ilvenen",
    "source": "Level 30 rare Crypt",
    "chestNumber": 12
  },
  {
    "from": "Lirosin",
    "source": "Level 25 Crypt",
    "chestNumber": 60
  },
  {
    "from": "Ilvenen",
    "source": "Level 30 epic Crypt",
    "chestNumber": 14
  },
  {
    "from": "poops",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Cewyn",
    "source": "Level 25 Crypt",
    "chestNumber": 12
  },
  {
    "from": "Cewyn",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 Crypt",
    "chestNumber": 22
  },
  {
    "from": "Cewyn",
    "source": "Arena",
    "chestNumber": 3
  },
  {
    "from": "Grande Inverno",
    "source": "Union of Triumph personal reward",
    "chestNumber": 8
  },
  {
    "from": "Strom A45",
    "source": "Level 25 Crypt",
    "chestNumber": 33
  },
  {
    "from": "Grande Inverno",
    "source": "Level 35 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Grande Inverno",
    "source": "Level 30 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Grande Inverno",
    "source": "Level 30 rare Crypt",
    "chestNumber": 22
  },
  {
    "from": "Logasticts SK",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Sashott",
    "source": "Level 25 Crypt",
    "chestNumber": 9
  },
  {
    "from": "Boadicee",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Sashott",
    "source": "Level 30 rare Crypt",
    "chestNumber": 53
  },
  {
    "from": "Strom A45",
    "source": "Level 20 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Sashott",
    "source": "Level 35 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Redman",
    "source": "Level 25 Crypt",
    "chestNumber": 89
  },
  {
    "from": "Strom A45",
    "source": "Level 25 epic Crypt",
    "chestNumber": 12
  },
  {
    "from": "Fobor",
    "source": "Level 25 Crypt",
    "chestNumber": 12
  },
  {
    "from": "Fobor",
    "source": "Level 30 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "Fobor",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "TheLeo",
    "source": "Epic Inferno squad",
    "chestNumber": 3
  },
  {
    "from": "Tygojind",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "G Babies",
    "source": "Level 25 Crypt",
    "chestNumber": 17
  },
  {
    "from": "Tygojind",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Tygojind",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kabandis",
    "source": "Level 25 Crypt",
    "chestNumber": 13
  },
  {
    "from": "Kabandis",
    "source": "Level 30 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Eyanin",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Eyanin",
    "source": "Level 25 Crypt",
    "chestNumber": 58
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Grimsborith Orik",
    "source": "Level 25 rare Crypt",
    "chestNumber": 8
  },
  {
    "from": "Grimsborith Orik",
    "source": "Level 30 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Redman",
    "source": "Level 30 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Redman",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Nerneen",
    "source": "Level 25 Crypt",
    "chestNumber": 143
  },
  {
    "from": "Onurb",
    "source": "Level 25 Crypt",
    "chestNumber": 39
  },
  {
    "from": "Logasticts SK",
    "source": "Level 25 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Supergiri",
    "source": "Level 25 rare Crypt",
    "chestNumber": 200
  },
  {
    "from": "Logasticts SK",
    "source": "Level 25 Crypt",
    "chestNumber": 58
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 Crypt",
    "chestNumber": 109
  },
  {
    "from": "Logasticts SK",
    "source": "Level 20 Crypt",
    "chestNumber": 52
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 epic Crypt",
    "chestNumber": 24
  },
  {
    "from": "Cliffhanger",
    "source": "Level 25 Crypt",
    "chestNumber": 45
  },
  {
    "from": "Athena",
    "source": "Level 25 epic Crypt",
    "chestNumber": 10
  },
  {
    "from": "Onurb",
    "source": "Level 30 epic Crypt",
    "chestNumber": 17
  },
  {
    "from": "Moginn",
    "source": "Level 25 Crypt",
    "chestNumber": 16
  },
  {
    "from": "Cliffhanger",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "TheLeo",
    "source": "Level 25 Crypt",
    "chestNumber": 9
  },
  {
    "from": "TheLeo",
    "source": "Level 30 rare Crypt",
    "chestNumber": 21
  },
  {
    "from": "TheLeo",
    "source": "Level 35 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 25 Crypt",
    "chestNumber": 36
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 30 rare Crypt",
    "chestNumber": 13
  },
  {
    "from": "Moonlight",
    "source": "Level 25 Crypt",
    "chestNumber": 99
  },
  {
    "from": "Gardashura",
    "source": "Level 25 Crypt",
    "chestNumber": 51
  },
  {
    "from": "Kabandis",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Emil SK 1",
    "source": "Level 25 Crypt",
    "chestNumber": 21
  },
  {
    "from": "Keleve",
    "source": "Level 35 epic Crypt",
    "chestNumber": 20
  },
  {
    "from": "Keleve",
    "source": "Level 30 rare Crypt",
    "chestNumber": 20
  },
  {
    "from": "Keleve",
    "source": "Level 25 Crypt",
    "chestNumber": 20
  },
  {
    "from": "Auth",
    "source": "Level 25 Crypt",
    "chestNumber": 16
  },
  {
    "from": "Metilar",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Metilar",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Gardashura",
    "source": "Level 25 epic Crypt",
    "chestNumber": 22
  },
  {
    "from": "Gardashura",
    "source": "Level 30 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "Ilvenen",
    "source": "Union of Triumph personal reward",
    "chestNumber": 8
  },
  {
    "from": "Gardashura",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Metilar",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Metilar",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Metilar",
    "source": "Level 25 rare Crypt",
    "chestNumber": 12
  },
  {
    "from": "Metilar",
    "source": "Level 25 Crypt",
    "chestNumber": 26
  },
  {
    "from": "Strom A45",
    "source": "Level 15 Crypt",
    "chestNumber": 1
  },
  {
    "from": "wil",
    "source": "Level 30 epic Crypt",
    "chestNumber": 15
  },
  {
    "from": "viking sv",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Maninod",
    "source": "Level 25 Crypt",
    "chestNumber": 5
  },
  {
    "from": "viking sv",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Maninod",
    "source": "Level 30 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Falcon Eye",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Falcon Eye",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "WODORY",
    "source": "Level 25 Crypt",
    "chestNumber": 32
  },
  {
    "from": "WODORY",
    "source": "Level 25 Citadel",
    "chestNumber": 7
  },
  {
    "from": "Cewyn",
    "source": "Level 30 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Cewyn",
    "source": "Level 30 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Cliffhanger",
    "source": "Level 35 epic Crypt",
    "chestNumber": 13
  },
  {
    "from": "Nerneen",
    "source": "Level 25 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Cliffhanger",
    "source": "Level 30 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Cliffhanger",
    "source": "Level 25 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Tefur",
    "source": "Level 25 Crypt",
    "chestNumber": 50
  },
  {
    "from": "Tefur",
    "source": "Level 19 heroic Monster",
    "chestNumber": 1
  },
  {
    "from": "Moginn",
    "source": "Level 35 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Tefur",
    "source": "Level 30 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Nerneen",
    "source": "Level 30 rare Crypt",
    "chestNumber": 11
  },
  {
    "from": "Cliffhanger",
    "source": "Level 30 rare Crypt",
    "chestNumber": 21
  },
  {
    "from": "Cliffhanger",
    "source": "Level 25 rare Crypt",
    "chestNumber": 26
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 rare Crypt",
    "chestNumber": 14
  },
  {
    "from": "Rainbrand",
    "source": "Level 30 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Onurb",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "nomad",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "BiG G",
    "source": "Level 30 rare Crypt",
    "chestNumber": 7
  },
  {
    "from": "Portal master",
    "source": "Epic Inferno squad",
    "chestNumber": 3
  },
  {
    "from": "Henry",
    "source": "Epic Inferno squad",
    "chestNumber": 3
  },
  {
    "from": "MBAH IV",
    "source": "Level 25 Crypt",
    "chestNumber": 61
  },
  {
    "from": "MBAH IV",
    "source": "Level 25 rare Crypt",
    "chestNumber": 45
  },
  {
    "from": "BiG G",
    "source": "Level 20 Crypt",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 10 Crypt",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 5 Crypt",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 25 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "MBAH IV",
    "source": "Level 30 epic Crypt",
    "chestNumber": 15
  },
  {
    "from": "Gilgamesh",
    "source": "Level 25 Crypt",
    "chestNumber": 9
  },
  {
    "from": "Gilgamesh",
    "source": "Level 30 rare Crypt",
    "chestNumber": 56
  },
  {
    "from": "Gilgamesh",
    "source": "Level 25 rare Crypt",
    "chestNumber": 58
  },
  {
    "from": "Ballage",
    "source": "Level 25 Crypt",
    "chestNumber": 47
  },
  {
    "from": "Ballage",
    "source": "Level 30 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Falcon Eye",
    "source": "Level 25 rare Crypt",
    "chestNumber": 15
  },
  {
    "from": "Gilgamesh",
    "source": "Level 35 epic Crypt",
    "chestNumber": 46
  },
  {
    "from": "zippy",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "zippy",
    "source": "Level 30 Citadel",
    "chestNumber": 5
  },
  {
    "from": "Anfir",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 25 Crypt",
    "chestNumber": 57
  },
  {
    "from": "Sashott",
    "source": "Level 30 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Vakula",
    "source": "Level 20 Crypt",
    "chestNumber": 84
  },
  {
    "from": "Vakula",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Vakula",
    "source": "Level 30 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Vakula",
    "source": "Level 30 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "Anfir",
    "source": "Level 25 Crypt",
    "chestNumber": 12
  },
  {
    "from": "Vakula",
    "source": "Level 25 Crypt",
    "chestNumber": 46
  },
  {
    "from": "Kizil Elma",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "GAGARIN",
    "source": "Level 30 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "GAGARIN",
    "source": "Level 25 rare Crypt",
    "chestNumber": 11
  },
  {
    "from": "Moginn",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "Gromuro them Babies",
    "source": "Clan wealth",
    "chestNumber": 5
  },
  {
    "from": "Matija Gubec",
    "source": "Level 35 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Matija Gubec",
    "source": "Level 25 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Babei",
    "source": "Level 20 Crypt",
    "chestNumber": 5
  },
  {
    "from": "Jurandowna",
    "source": "Level 30 rare Crypt",
    "chestNumber": 8
  },
  {
    "from": "Babei",
    "source": "Level 15 Crypt",
    "chestNumber": 5
  },
  {
    "from": "Fobor",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Babei",
    "source": "Level 10 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Babei",
    "source": "Level 15 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Babei",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "poops",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Tygojind",
    "source": "Level 10 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kalabar",
    "source": "Level 25 Crypt",
    "chestNumber": 39
  },
  {
    "from": "poops",
    "source": "Level 20 Citadel",
    "chestNumber": 1
  },
  {
    "from": "poops",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Tygojind",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Amginad",
    "source": "Level 25 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Grande Inverno",
    "source": "Level 25 epic Crypt",
    "chestNumber": 9
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 epic Crypt",
    "chestNumber": 8
  },
  {
    "from": "Redman",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Portal master",
    "source": "Level 15 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Portal master",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "Strom A45",
    "source": "Level 20 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Nejinn IV",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Strom A45",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Kalabar",
    "source": "Level 35 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Kalabar",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Boadicee",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "kimo",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Strom A45",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Boadicee",
    "source": "Level 30 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "kimo",
    "source": "Level 30 epic Crypt",
    "chestNumber": 10
  },
  {
    "from": "kimo",
    "source": "Level 25 Crypt",
    "chestNumber": 20
  },
  {
    "from": "Supergiri",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Henry",
    "source": "Level 30 rare Crypt",
    "chestNumber": 19
  },
  {
    "from": "Henry",
    "source": "Level 25 rare Crypt",
    "chestNumber": 21
  },
  {
    "from": "Henry",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kabandis",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Kabandis",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Grimsborith Orik",
    "source": "Level 25 Crypt",
    "chestNumber": 49
  },
  {
    "from": "Grimsborith Orik",
    "source": "Level 25 epic Crypt",
    "chestNumber": 11
  },
  {
    "from": "Emarith",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Emarith",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Level 35 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Ollo II",
    "source": "Level 30 rare Crypt",
    "chestNumber": 10
  },
  {
    "from": "Ollo II",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Ollo II",
    "source": "Level 35 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Ollo II",
    "source": "Level 25 Crypt",
    "chestNumber": 16
  },
  {
    "from": "Tojakora",
    "source": "Level 25 epic Crypt",
    "chestNumber": 29
  },
  {
    "from": "Tojakora",
    "source": "Level 25 Crypt",
    "chestNumber": 7
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Falcon Eye",
    "source": "Union of Triumph personal reward",
    "chestNumber": 8
  },
  {
    "from": "Rainbrand",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Fankayel",
    "source": "Clan wealth",
    "chestNumber": 5
  },
  {
    "from": "Lirosin",
    "source": "Level 30 rare Crypt",
    "chestNumber": 8
  },
  {
    "from": "Lirosin",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Rainbrand",
    "source": "Union of Triumph personal reward",
    "chestNumber": 7
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 5 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Maninod",
    "source": "Level 30 rare Crypt",
    "chestNumber": 24
  },
  {
    "from": "Emarith",
    "source": "Level 30 epic Crypt",
    "chestNumber": 12
  },
  {
    "from": "Eyanin",
    "source": "Level 25 epic Crypt",
    "chestNumber": 12
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Fankayel",
    "source": "Epic Inferno squad",
    "chestNumber": 2
  },
  {
    "from": "Eyanin",
    "source": "Level 25 rare Crypt",
    "chestNumber": 12
  },
  {
    "from": "Athena",
    "source": "Level 30 Citadel",
    "chestNumber": 3
  },
  {
    "from": "Athena",
    "source": "Level 22 heroic Monster",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Eyanin",
    "source": "Level 25 Citadel",
    "chestNumber": 10
  },
  {
    "from": "Feninor",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Feninor",
    "source": "Level 30 epic Crypt",
    "chestNumber": 15
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 20 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Moonlight",
    "source": "Level 30 rare Crypt",
    "chestNumber": 10
  },
  {
    "from": "Fankayel",
    "source": "Level 25 epic Crypt",
    "chestNumber": 68
  },
  {
    "from": "Anton",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Falcon Eye",
    "source": "Bank",
    "chestNumber": 6
  },
  {
    "from": "Blue Lion",
    "source": "Level 30 epic Crypt",
    "chestNumber": 11
  },
  {
    "from": "Leonidas",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Blue Lion",
    "source": "Level 30 rare Crypt",
    "chestNumber": 24
  },
  {
    "from": "Grande Inverno",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Rob",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "Gardashura",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 35 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Fallegin",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Anfir",
    "source": "Union of Triumph personal reward",
    "chestNumber": 8
  },
  {
    "from": "Anfir",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Anfir",
    "source": "Level 15 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Feninor",
    "source": "Epic Inferno squad",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 35 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 10 Citadel",
    "chestNumber": 3
  },
  {
    "from": "Anton",
    "source": "Epic Inferno squad",
    "chestNumber": 21
  },
  {
    "from": "Nerdanilas",
    "source": "Level 30 epic Crypt",
    "chestNumber": 18
  },
  {
    "from": "Anton",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Rasses74",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 3
  },
  {
    "from": "Anton",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 3
  },
  {
    "from": "Nerdanilas",
    "source": "Level 20 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Gromuro them Babies",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Rasses74",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "zippy",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Kizil Elma",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Redman",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Grande Inverno",
    "source": "Level 15 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Gromuro them Babies",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 2
  },
  {
    "from": "Feninor",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 2
  },
  {
    "from": "Rasses74",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Maninod",
    "source": "Authority Rush tournament",
    "chestNumber": 4
  },
  {
    "from": "G Babies",
    "source": "Level 20 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "TTT",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 2
  },
  {
    "from": "G Babies",
    "source": "Level 25 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Feninor",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Grande Inverno",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "GAGARIN",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Metilar",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Henry",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 3
  },
  {
    "from": "Moonlight",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 2
  },
  {
    "from": "nomad",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Fallegin",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Moonlight",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Marauders",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Blue Lion",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Fallegin",
    "source": "Level 25 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "GAGARIN",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Emil SK 1",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Sashott",
    "source": "Authority Rush tournament",
    "chestNumber": 3
  },
  {
    "from": "Anton",
    "source": "Lvl 25-29 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Brakus",
    "source": "Epic Undead squad",
    "chestNumber": 2
  },
  {
    "from": "Matija Gubec",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Brakus",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Blue Lion",
    "source": "Authority Rush tournament",
    "chestNumber": 4
  },
  {
    "from": "Matija Gubec",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Matija Gubec",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Falcon Eye",
    "source": "Authority Rush tournament",
    "chestNumber": 4
  },
  {
    "from": "Karl Killer",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Karl Killer",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "Moginn",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Karl Killer",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "GAGARIN",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Anton",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Brakus",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "Nejinn IV",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Babei",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Rasses74",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Nejinn IV",
    "source": "Level 35 epic Crypt",
    "chestNumber": 8
  },
  {
    "from": "Gardashura",
    "source": "Lvl 35-39 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Babei",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Amginad",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Brakus",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Kizil Elma",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Mag junior",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Brakus",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Kizil Elma",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Mag junior",
    "source": "Authority Rush tournament",
    "chestNumber": 4
  },
  {
    "from": "Sashott",
    "source": "Epic Undead squad",
    "chestNumber": 2
  },
  {
    "from": "Gromuro them Babies",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Ollo II",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Redman",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Brakus",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Blue Lion",
    "source": "Level 25 rare Crypt",
    "chestNumber": 32
  },
  {
    "from": "zippy",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Eyanin",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "poops",
    "source": "Authority Rush tournament",
    "chestNumber": 5
  },
  {
    "from": "Amginad",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "poops",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "viking sv",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Tefur",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "viking sv",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Tojakora",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Darrinel",
    "source": "Level 35 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Cewyn",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Cewyn",
    "source": "Authority Rush tournament",
    "chestNumber": 5
  },
  {
    "from": "Strom A45",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Cewyn",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Strom A45",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Lirosin",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Cewyn",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Tygojind",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Tygojind",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "MII Mighty Micho",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Ares",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Kabandis",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "Marond",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Tygojind",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Tygojind",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "wil",
    "source": "Level 30 rare Crypt",
    "chestNumber": 10
  },
  {
    "from": "Tefur",
    "source": "Level 25 rare Crypt",
    "chestNumber": 15
  },
  {
    "from": "Lirosin",
    "source": "Bank",
    "chestNumber": 3
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Fankayel",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Keleve",
    "source": "Epic Undead squad",
    "chestNumber": 5
  },
  {
    "from": "Keleve",
    "source": "Lvl 30-34 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Falcon Eye",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Fankayel",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "Maninod",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Maninod",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Keleve",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Fallegin",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Fallegin",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Fallegin",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Fallegin",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "MBAH IV",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Karl Killer",
    "source": "Level 10 Crypt",
    "chestNumber": 1
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Keleve",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Eyanin",
    "source": "Authority Rush tournament",
    "chestNumber": 3
  },
  {
    "from": "Strom A45",
    "source": "Lvl 35-39 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Badur",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Sashott",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Nejinn IV",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Boadicee",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Nejinn IV",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Rob",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Elric de Melnibonee",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Nejinn IV",
    "source": "Lvl 35-39 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Ballage",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Boadicee",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 2
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Authority Rush tournament",
    "chestNumber": 3
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Epic Undead squad",
    "chestNumber": 1
  },
  {
    "from": "Cliffhanger",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Anfir",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Gardashura",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "Jurandowna",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "Nerneen",
    "source": "Authority Rush tournament",
    "chestNumber": 2
  },
  {
    "from": "Gardashura",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Anfir",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Boadicee",
    "source": "Lvl 45 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Morana",
    "source": "Authority Rush tournament",
    "chestNumber": 4
  },
  {
    "from": "Nerneen",
    "source": "Level 30 Citadel",
    "chestNumber": 7
  },
  {
    "from": "Emil SK 1",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "WODORY",
    "source": "Lvl 40-44 Raid Runic squad",
    "chestNumber": 1
  },
  {
    "from": "Fallegin",
    "source": "Authority Rush tournament",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Bank",
    "chestNumber": 3
  }
];
