// Generated by text_to_data_js.py
// Raw rows parsed: 4717 | Skipped: 0 | Groups: 434
const rawDataLastUpdatedIso = "2026-04-21T13:59:27.841532Z";
const rawData = [
  {
    "from": "Falcon Eye",
    "source": "Level 25 Crypt",
    "chestNumber": 20
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 25 Crypt",
    "chestNumber": 34
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 Crypt",
    "chestNumber": 77
  },
  {
    "from": "Cewyn",
    "source": "Level 25 Crypt",
    "chestNumber": 17
  },
  {
    "from": "TheLeo",
    "source": "Level 35 epic Crypt",
    "chestNumber": 9
  },
  {
    "from": "Darrinel",
    "source": "Level 25 Crypt",
    "chestNumber": 33
  },
  {
    "from": "Gukora",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Morana",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Athena $",
    "source": "Level 20 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Kizil Elma",
    "source": "Level 25 Crypt",
    "chestNumber": 30
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 5
  },
  {
    "from": "Rasses74",
    "source": "Level 25 Crypt",
    "chestNumber": 57
  },
  {
    "from": "Kabandis",
    "source": "Level 25 Crypt",
    "chestNumber": 8
  },
  {
    "from": "Cliffhanger",
    "source": "Level 25 Crypt",
    "chestNumber": 8
  },
  {
    "from": "Kabandis",
    "source": "Level 30 rare Crypt",
    "chestNumber": 7
  },
  {
    "from": "Brakus",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Kizil Elma",
    "source": "Level 25 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Feninor",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Lasius",
    "source": "Level 25 Crypt",
    "chestNumber": 22
  },
  {
    "from": "Cewyn",
    "source": "Level 25 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Anton",
    "source": "Level 5 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 7
  },
  {
    "from": "Kizil Elma",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Rasses74",
    "source": "Level 35 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Feninor",
    "source": "Level 20 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Brakus",
    "source": "Level 25 Crypt",
    "chestNumber": 34
  },
  {
    "from": "Kizil Elma",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Kabandis",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 4
  },
  {
    "from": "Grimsborith Orik",
    "source": "Level 25 Crypt",
    "chestNumber": 2
  },
  {
    "from": "poops",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Rasses74",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Lasius",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "wil",
    "source": "Level 25 Crypt",
    "chestNumber": 42
  },
  {
    "from": "Kabandis",
    "source": "Level 30 Citadel",
    "chestNumber": 11
  },
  {
    "from": "Kizil Elma",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "poops",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "GAGARIN",
    "source": "Level 25 Crypt",
    "chestNumber": 27
  },
  {
    "from": "Ballage",
    "source": "Level 25 Crypt",
    "chestNumber": 10
  },
  {
    "from": "sk",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "Blue Lion",
    "source": "Level 25 Crypt",
    "chestNumber": 37
  },
  {
    "from": "Bardin",
    "source": "Level 25 Crypt",
    "chestNumber": 16
  },
  {
    "from": "Bardin",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "sk",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Feninor",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 3
  },
  {
    "from": "Feninor",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "Fallegin",
    "source": "Level 15 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Rob",
    "source": "Level 25 Crypt",
    "chestNumber": 98
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Arena",
    "chestNumber": 2
  },
  {
    "from": "sk",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Bardin",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "TTT",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Bardin",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "GAGARIN",
    "source": "Level 30 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 25 Crypt",
    "chestNumber": 19
  },
  {
    "from": "Oleg Ya",
    "source": "Level 25 Crypt",
    "chestNumber": 30
  },
  {
    "from": "GAGARIN",
    "source": "Level 25 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "Oleg Ya",
    "source": "Level 20 Crypt",
    "chestNumber": 3
  },
  {
    "from": "GAGARIN",
    "source": "Level 30 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Oleg Ya",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Bardin",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Athena",
    "source": "Union of Triumph personal reward",
    "chestNumber": 6
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 25 Crypt",
    "chestNumber": 76
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "BlizZy",
    "source": "Level 5 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 25 Crypt",
    "chestNumber": 25
  },
  {
    "from": "Fallegin",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Fallegin",
    "source": "Level 25 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "MBAH IV",
    "source": "Level 25 Crypt",
    "chestNumber": 20
  },
  {
    "from": "BlizZy",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 30 rare Crypt",
    "chestNumber": 31
  },
  {
    "from": "GAGARIN",
    "source": "Level 25 epic Crypt",
    "chestNumber": 11
  },
  {
    "from": "Brakus",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 11
  },
  {
    "from": "Oleg Ya",
    "source": "Level 30 Citadel",
    "chestNumber": 10
  },
  {
    "from": "Tygojind",
    "source": "Level 25 Crypt",
    "chestNumber": 37
  },
  {
    "from": "Tygojind",
    "source": "Level 25 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Fobor",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Vakula",
    "source": "Level 20 Crypt",
    "chestNumber": 32
  },
  {
    "from": "Vakula",
    "source": "Level 25 Crypt",
    "chestNumber": 27
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 25 Citadel",
    "chestNumber": 12
  },
  {
    "from": "Fobor",
    "source": "Level 25 Crypt",
    "chestNumber": 30
  },
  {
    "from": "Mag junior",
    "source": "Level 20 Crypt",
    "chestNumber": 14
  },
  {
    "from": "Supergiri",
    "source": "Level 10 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 Citadel",
    "chestNumber": 2
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "Jedi Tano",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Jedi Tano",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 30 Citadel",
    "chestNumber": 24
  },
  {
    "from": "Vakula",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Vakula",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Soyin",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Tygojind",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Brakus",
    "source": "Level 30-34 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Fankayel",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Vakula",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Tefur",
    "source": "Level 25 Crypt",
    "chestNumber": 65
  },
  {
    "from": "Anton",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Oleg Ya",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Tefur",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 Crypt",
    "chestNumber": 11
  },
  {
    "from": "Sashott",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Ares",
    "source": "Level 25 Crypt",
    "chestNumber": 118
  },
  {
    "from": "Sashott",
    "source": "Level 30 rare Crypt",
    "chestNumber": 7
  },
  {
    "from": "Ares",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 epic Crypt",
    "chestNumber": 14
  },
  {
    "from": "Amginad",
    "source": "Level 25 Crypt",
    "chestNumber": 23
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 rare Crypt",
    "chestNumber": 20
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 30 Citadel",
    "chestNumber": 13
  },
  {
    "from": "wil",
    "source": "Level 30 rare Crypt",
    "chestNumber": 11
  },
  {
    "from": "Maninod",
    "source": "Level 25 Crypt",
    "chestNumber": 11
  },
  {
    "from": "Auth",
    "source": "Level 25 Crypt",
    "chestNumber": 28
  },
  {
    "from": "BiG G",
    "source": "Level 15 Crypt",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 10 Crypt",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 3
  },
  {
    "from": "Gardashura",
    "source": "Level 25 Crypt",
    "chestNumber": 41
  },
  {
    "from": "BiG G",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "Anton CP City",
    "source": "Level 10 Crypt",
    "chestNumber": 2
  },
  {
    "from": "wil",
    "source": "Level 25 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Eyanin",
    "source": "Level 25 Crypt",
    "chestNumber": 17
  },
  {
    "from": "WODORY",
    "source": "Level 20 Citadel",
    "chestNumber": 2
  },
  {
    "from": "WODORY",
    "source": "Level 25 Crypt",
    "chestNumber": 36
  },
  {
    "from": "Lirosin",
    "source": "Level 25 Crypt",
    "chestNumber": 34
  },
  {
    "from": "Auth",
    "source": "Level 23 heroic Monster",
    "chestNumber": 1
  },
  {
    "from": "TTT",
    "source": "Level 10 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Lirosin",
    "source": "Level 30 rare Crypt",
    "chestNumber": 11
  },
  {
    "from": "Auth",
    "source": "Level 22 heroic Monster",
    "chestNumber": 1
  },
  {
    "from": "Lirosin",
    "source": "Level 30 epic Crypt",
    "chestNumber": 12
  },
  {
    "from": "Tygojind",
    "source": "Level 30 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "WODORY",
    "source": "Level 25 Citadel",
    "chestNumber": 5
  },
  {
    "from": "Anton",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Nejinn IV",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Amginad",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "Eyanin",
    "source": "Level 25 rare Crypt",
    "chestNumber": 11
  },
  {
    "from": "Nejinn IV",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Sashott",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 3
  },
  {
    "from": "Babei",
    "source": "Level 25 Crypt",
    "chestNumber": 6
  },
  {
    "from": "Nejinn IV",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Babei",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Fobor",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Eyanin",
    "source": "Level 25 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Badur",
    "source": "Level 25 Crypt",
    "chestNumber": 22
  },
  {
    "from": "Marauders",
    "source": "Level 30 rare Crypt",
    "chestNumber": 33
  },
  {
    "from": "Marauders",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Tefur",
    "source": "Level 30 epic Crypt",
    "chestNumber": 16
  },
  {
    "from": "Marauders",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Brakus",
    "source": "Level 30 epic Crypt",
    "chestNumber": 23
  },
  {
    "from": "Keleve",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Falcon Eye",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 4
  },
  {
    "from": "Boadicee",
    "source": "Level 25 Crypt",
    "chestNumber": 12
  },
  {
    "from": "Brakus",
    "source": "Level 30 rare Crypt",
    "chestNumber": 17
  },
  {
    "from": "Cewyn",
    "source": "Level 25 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Keleve",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Marauders",
    "source": "Level 30 Citadel",
    "chestNumber": 25
  },
  {
    "from": "TH R YLOSII",
    "source": "Level 25 epic Crypt",
    "chestNumber": 12
  },
  {
    "from": "Keleve",
    "source": "Level 35 epic Crypt",
    "chestNumber": 28
  },
  {
    "from": "Keleve",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "TH R YLOSII",
    "source": "Level 25 rare Crypt",
    "chestNumber": 7
  },
  {
    "from": "kimo",
    "source": "Level 25 Crypt",
    "chestNumber": 16
  },
  {
    "from": "TH R YLOSII",
    "source": "Level 25 Crypt",
    "chestNumber": 7
  },
  {
    "from": "Cewyn",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Cewyn",
    "source": "Level 30 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "Redman",
    "source": "Level 25 Crypt",
    "chestNumber": 31
  },
  {
    "from": "Kalabar",
    "source": "Level 30 Citadel",
    "chestNumber": 24
  },
  {
    "from": "viking sv",
    "source": "Level 20 Crypt",
    "chestNumber": 1
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Tojakora",
    "source": "Level 25 Crypt",
    "chestNumber": 19
  },
  {
    "from": "Marauders",
    "source": "Level 30 heroic Monster",
    "chestNumber": 4
  },
  {
    "from": "Gilgamesh",
    "source": "Level 25 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Sir Dori",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "Matija Gubec",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Gilgamesh",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Nerneen",
    "source": "Level 25 Crypt",
    "chestNumber": 11
  },
  {
    "from": "Lirosin",
    "source": "Level 25 rare Crypt",
    "chestNumber": 8
  },
  {
    "from": "Henry",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 7
  },
  {
    "from": "Henry",
    "source": "Level 25 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Z",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 Crypt",
    "chestNumber": 13
  },
  {
    "from": "Matija Gubec",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "Marond",
    "source": "Level 25 Crypt",
    "chestNumber": 10
  },
  {
    "from": "Carlos Rengoku",
    "source": "Level 20 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 6
  },
  {
    "from": "Carlos Rengoku",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kalabar",
    "source": "Level 30 rare Crypt",
    "chestNumber": 30
  },
  {
    "from": "Marond",
    "source": "Level 35 epic Crypt",
    "chestNumber": 8
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 Citadel",
    "chestNumber": 4
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "Marond",
    "source": "Level 25 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Marond",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kalabar",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Marond",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 3
  },
  {
    "from": "Tefur",
    "source": "Level 25 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Tefur",
    "source": "Level 19 heroic Monster",
    "chestNumber": 6
  },
  {
    "from": "Carlos Rengoku",
    "source": "Level 10 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Tefur",
    "source": "Level 18 heroic Monster",
    "chestNumber": 4
  },
  {
    "from": "Nerneen",
    "source": "Level 30 rare Crypt",
    "chestNumber": 7
  },
  {
    "from": "Nerneen",
    "source": "Level 25 epic Crypt",
    "chestNumber": 8
  },
  {
    "from": "Emil SK 1",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Level 35 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Falcon Eye",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 3
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Level 20 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Gromuro them Babies",
    "source": "Clan wealth",
    "chestNumber": 4
  },
  {
    "from": "Fallegin",
    "source": "Level 25 Crypt",
    "chestNumber": 6
  },
  {
    "from": "Fallegin",
    "source": "Level 30 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Fallegin",
    "source": "Level 30 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "Logasticts SK",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 epic Crypt",
    "chestNumber": 21
  },
  {
    "from": "Rainbrand",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Logasticts SK",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Onurb",
    "source": "Level 25 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Onurb",
    "source": "Level 20 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 25 Crypt",
    "chestNumber": 11
  },
  {
    "from": "Athena",
    "source": "Level 30 Citadel",
    "chestNumber": 4
  },
  {
    "from": "DocHolliblazed",
    "source": "Level 10 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Blue Lion",
    "source": "Level 25 rare Crypt",
    "chestNumber": 14
  },
  {
    "from": "Grande Inverno",
    "source": "Level 25 Crypt",
    "chestNumber": 9
  },
  {
    "from": "Cliffhanger",
    "source": "Level 35 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Cliffhanger",
    "source": "Level 30 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Cliffhanger",
    "source": "Level 25 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Feninor",
    "source": "Level 35 epic Crypt",
    "chestNumber": 10
  },
  {
    "from": "Rob",
    "source": "Level 30 Citadel",
    "chestNumber": 9
  },
  {
    "from": "Gardashura",
    "source": "Level 25 epic Crypt",
    "chestNumber": 15
  },
  {
    "from": "Gardashura",
    "source": "Level 25 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "Gardashura",
    "source": "Level 25 Citadel",
    "chestNumber": 13
  },
  {
    "from": "Maninod",
    "source": "Level 20 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Gardashura",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Maninod",
    "source": "Level 30 epic Crypt",
    "chestNumber": 8
  },
  {
    "from": "Maninod",
    "source": "Level 30 rare Crypt",
    "chestNumber": 7
  },
  {
    "from": "viking sv",
    "source": "Level 25 Crypt",
    "chestNumber": 16
  },
  {
    "from": "viking sv",
    "source": "Level 30 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 Crypt",
    "chestNumber": 14
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "Tefur",
    "source": "Level 17 heroic Monster",
    "chestNumber": 2
  },
  {
    "from": "Tefur",
    "source": "Level 22 heroic Monster",
    "chestNumber": 1
  },
  {
    "from": "Grande Inverno",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Tefur",
    "source": "Level 20 heroic Monster",
    "chestNumber": 1
  },
  {
    "from": "DocHolliblazed",
    "source": "Level 25 epic Crypt",
    "chestNumber": 15
  },
  {
    "from": "DocHolliblazed",
    "source": "Level 27 heroic Monster",
    "chestNumber": 3
  },
  {
    "from": "Fallegin",
    "source": "Level 25 Citadel",
    "chestNumber": 8
  },
  {
    "from": "Bardin",
    "source": "Level 30 Citadel",
    "chestNumber": 14
  },
  {
    "from": "Maninod",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Mkaan",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Metilar",
    "source": "Level 25 Citadel",
    "chestNumber": 10
  },
  {
    "from": "Henry",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 2
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 30 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "BiG G",
    "source": "Level 35 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Henry",
    "source": "Level 40-44 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "BiG G",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Metilar",
    "source": "Level 30 Citadel",
    "chestNumber": 5
  },
  {
    "from": "Kalabar",
    "source": "Level 25 Crypt",
    "chestNumber": 42
  },
  {
    "from": "Supergiri",
    "source": "Level 25 Crypt",
    "chestNumber": 150
  },
  {
    "from": "Metilar",
    "source": "Level 25 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "Metilar",
    "source": "Level 30 rare Crypt",
    "chestNumber": 7
  },
  {
    "from": "Leonidas",
    "source": "Level 25 rare Crypt",
    "chestNumber": 11
  },
  {
    "from": "Metilar",
    "source": "Level 25 Crypt",
    "chestNumber": 26
  },
  {
    "from": "nomad",
    "source": "Level 25 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Mag junior",
    "source": "Level 25 Crypt",
    "chestNumber": 85
  },
  {
    "from": "Ilvenen",
    "source": "Level 25 Crypt",
    "chestNumber": 27
  },
  {
    "from": "Ilvenen",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Anfir",
    "source": "Level 25 Crypt",
    "chestNumber": 7
  },
  {
    "from": "Ilvenen",
    "source": "Level 30 epic Crypt",
    "chestNumber": 11
  },
  {
    "from": "MBAH IV",
    "source": "Level 25 rare Crypt",
    "chestNumber": 29
  },
  {
    "from": "Bardin",
    "source": "Level 35-39 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Ilvenen",
    "source": "Level 30 Citadel",
    "chestNumber": 24
  },
  {
    "from": "Nerneen",
    "source": "Level 25 rare Crypt",
    "chestNumber": 28
  },
  {
    "from": "MBAH IV",
    "source": "Level 30 epic Crypt",
    "chestNumber": 11
  },
  {
    "from": "Ilvenen",
    "source": "Level 30 rare Crypt",
    "chestNumber": 16
  },
  {
    "from": "Athena",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Rob",
    "source": "Level 30 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "Supergiri",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Falcon Eye",
    "source": "Bank",
    "chestNumber": 6
  },
  {
    "from": "Lirosin",
    "source": "Bank",
    "chestNumber": 3
  },
  {
    "from": "Domina",
    "source": "Level 20 Crypt",
    "chestNumber": 5
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Brakus",
    "source": "Level 45 Vault of the Ancients",
    "chestNumber": 1
  },
  {
    "from": "Lady LT",
    "source": "Level 25 Crypt",
    "chestNumber": 2
  },
  {
    "from": "Lady LT",
    "source": "Clan wealth",
    "chestNumber": 3
  },
  {
    "from": "ChestCounter T",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Vakula",
    "source": "Level 15 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Anton",
    "source": "Level 30 rare Crypt",
    "chestNumber": 101
  },
  {
    "from": "Feninor",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "TheLeo",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Feninor",
    "source": "Level 25 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Leonidas",
    "source": "Level 25 Crypt",
    "chestNumber": 7
  },
  {
    "from": "Kizil Elma",
    "source": "Level 20 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Sashott",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Athena",
    "source": "Level 20 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Darrinel",
    "source": "Level 35 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Matija Gubec",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Matija Gubec",
    "source": "Level 30 rare Crypt",
    "chestNumber": 29
  },
  {
    "from": "Ilvenen",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "Matija Gubec",
    "source": "Level 25 rare Crypt",
    "chestNumber": 10
  },
  {
    "from": "Babei",
    "source": "Level 20 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Babei",
    "source": "Level 15 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Grande Inverno",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Babei",
    "source": "Level 10 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Redman",
    "source": "Level 25 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "Redman",
    "source": "Level 30 epic Crypt",
    "chestNumber": 8
  },
  {
    "from": "Eyanin",
    "source": "Level 25 Citadel",
    "chestNumber": 7
  },
  {
    "from": "kimo",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Nejinn IV",
    "source": "Rise of the Ancients event",
    "chestNumber": 16
  },
  {
    "from": "Matija Gubec",
    "source": "Rise of the Ancients event",
    "chestNumber": 11
  },
  {
    "from": "TheLeo",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Karl Killer",
    "source": "Rise of the Ancients event",
    "chestNumber": 5
  },
  {
    "from": "Blue Lion",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Tefur",
    "source": "Rise of the Ancients event",
    "chestNumber": 6
  },
  {
    "from": "GAGARIN",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Darrinel",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Jurandowna",
    "source": "Rise of the Ancients event",
    "chestNumber": 11
  },
  {
    "from": "Rasses74",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Fobor",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Fankayel",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Emil SK 1",
    "source": "Rise of the Ancients event",
    "chestNumber": 7
  },
  {
    "from": "Rainbrand",
    "source": "Rise of the Ancients event",
    "chestNumber": 11
  },
  {
    "from": "Ballage",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Moginn",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Feninor",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Athena",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Carlos Rengoku",
    "source": "Rise of the Ancients event",
    "chestNumber": 15
  },
  {
    "from": "Lasius",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Amginad",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Gilgamesh",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Babei",
    "source": "Rise of the Ancients event",
    "chestNumber": 6
  },
  {
    "from": "kimo",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Redman",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Metilar",
    "source": "Rise of the Ancients event",
    "chestNumber": 16
  },
  {
    "from": "Henry",
    "source": "Rise of the Ancients event",
    "chestNumber": 15
  },
  {
    "from": "Keleve",
    "source": "Epic Ancient squad",
    "chestNumber": 225
  },
  {
    "from": "Tygojind",
    "source": "Rise of the Ancients event",
    "chestNumber": 11
  },
  {
    "from": "Gukora",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Nerdanilas",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Onurb",
    "source": "Rise of the Ancients event",
    "chestNumber": 11
  },
  {
    "from": "Gardashura",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Fallegin",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Grande Inverno",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Auth",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Jedi Tano",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "MBAH IV",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Portal master",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Brakus",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Nerneen",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Rob",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Rise of the Ancients event",
    "chestNumber": 11
  },
  {
    "from": "Keleve",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Ares",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "wil",
    "source": "Rise of the Ancients event",
    "chestNumber": 15
  },
  {
    "from": "Oleg Ya",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Kizil Elma",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Akinohn",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Falcon Eye",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Tygojind",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Badur",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Gromuro them Babies",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Eyanin",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Bardin",
    "source": "Rise of the Ancients event",
    "chestNumber": 11
  },
  {
    "from": "Ilvenen",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "viking sv",
    "source": "Rise of the Ancients event",
    "chestNumber": 15
  },
  {
    "from": "Sir Dori",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Vakula",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "Portal master",
    "source": "Epic Ancient squad",
    "chestNumber": 231
  },
  {
    "from": "Logasticts SK",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Cewyn",
    "source": "Rise of the Ancients event",
    "chestNumber": 4
  },
  {
    "from": "Mag junior",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Leonidas",
    "source": "Rise of the Ancients event",
    "chestNumber": 14
  },
  {
    "from": "Ballage",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Sashott",
    "source": "Rise of the Ancients event",
    "chestNumber": 15
  },
  {
    "from": "Jurandowna",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Rob",
    "source": "Mercenary Exchange",
    "chestNumber": 3
  },
  {
    "from": "TH R YLOSII",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "sk",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Athena",
    "source": "Level 25 epic Crypt",
    "chestNumber": 7
  },
  {
    "from": "poops",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Morana",
    "source": "Rise of the Ancients event",
    "chestNumber": 12
  },
  {
    "from": "viking sv",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Grimsborith Orik",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "MII Mighty Micho",
    "source": "Mercenary Exchange",
    "chestNumber": 2
  },
  {
    "from": "Oleg Ya",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "MII Mighty Micho",
    "source": "Level 30 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Carlos Rengoku",
    "source": "Mercenary Exchange",
    "chestNumber": 2
  },
  {
    "from": "TheLeo",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "wil",
    "source": "Level 30 epic Crypt",
    "chestNumber": 15
  },
  {
    "from": "SmokinLauren?",
    "source": "Rise of the Ancients event",
    "chestNumber": 15
  },
  {
    "from": "Fankayel",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Gromuro them Babies",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Falcon Eye",
    "source": "Level 25 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Falcon Eye",
    "source": "Level 25 rare Crypt",
    "chestNumber": 8
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 20 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 30 epic Crypt",
    "chestNumber": 12
  },
  {
    "from": "Marond",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 30 rare Crypt",
    "chestNumber": 9
  },
  {
    "from": "Fallegin",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "nomad",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Onurb",
    "source": "Mercenary Exchange",
    "chestNumber": 2
  },
  {
    "from": "Rainbrand",
    "source": "Level 30 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Metilar",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Rasses74",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Brakus",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Blue Lion",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Karl Killer",
    "source": "Level 30 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Karl Killer",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Amginad",
    "source": "Level 25 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 30 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Domina",
    "source": "Mercenary Exchange",
    "chestNumber": 3
  },
  {
    "from": "Brakus",
    "source": "Clan wealth",
    "chestNumber": 3
  },
  {
    "from": "Auth",
    "source": "Mercenary Exchange",
    "chestNumber": 2
  },
  {
    "from": "Z",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Rob",
    "source": "Level 35 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Ares",
    "source": "Mercenary Exchange",
    "chestNumber": 3
  },
  {
    "from": "Maninod",
    "source": "Level 25 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "Metilar",
    "source": "Level 25 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 25 rare Crypt",
    "chestNumber": 4
  },
  {
    "from": "WODORY",
    "source": "Rise of the Ancients event",
    "chestNumber": 18
  },
  {
    "from": "WODORY",
    "source": "Level 25 epic Crypt",
    "chestNumber": 14
  },
  {
    "from": "Leonidas",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "LARIS BellaTrix",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "viking sv",
    "source": "Level 20 Citadel",
    "chestNumber": 1
  },
  {
    "from": "viking sv",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "viking sv",
    "source": "Level 25 Citadel",
    "chestNumber": 4
  }
];
