// Generated by text_to_data_js.py
// Raw rows parsed: 2407 | Skipped: 0 | Groups: 181
const rawDataLastUpdatedIso = "2026-04-27T05:45:07.510883Z";
const rawData = [
  {
    "from": "SmokinLauren?",
    "source": "Level 30 epic Crypt",
    "chestNumber": 4
  },
  {
    "from": "Boadicee",
    "source": "Level 25 Crypt",
    "chestNumber": 12
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 30 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "Bardin",
    "source": "Level 20 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 25 Crypt",
    "chestNumber": 9
  },
  {
    "from": "SmokinLauren?",
    "source": "Level 25 Crypt",
    "chestNumber": 57
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 Crypt",
    "chestNumber": 11
  },
  {
    "from": "Gromuro them Babies",
    "source": "Event \"Trials of Olympus",
    "chestNumber": 500
  },
  {
    "from": "Kabandis",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Fallegin",
    "source": "Level 25 Crypt",
    "chestNumber": 6
  },
  {
    "from": "Karl Killer",
    "source": "Level 30 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Gromuro them Babies",
    "source": "Level 25 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Rasses74",
    "source": "Level 25 Crypt",
    "chestNumber": 35
  },
  {
    "from": "Karl Killer",
    "source": "Level 30 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "Ilvenen",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "wil",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Karl Killer",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Sashott",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Sashott",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "G Babies",
    "source": "Level 25 Crypt",
    "chestNumber": 5
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "sk",
    "source": "Level 35 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Nejinn IV",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Fallegin",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "G Babies",
    "source": "Level 20 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "GAGARIN",
    "source": "Level 25 Crypt",
    "chestNumber": 2
  },
  {
    "from": "sk",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "sk",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Tojakora",
    "source": "Bank",
    "chestNumber": 3
  },
  {
    "from": "Babei",
    "source": "Level 25 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Portal master",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Darrinel",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Logasticts SK",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Fallegin",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Ilvenen",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Redman",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "nomad",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Amginad",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Fankayel",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Vakula",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "wil",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Tygojind",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Jurandowna",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Maninod",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Feninor",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Ragnar Lothbrok",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Kabandis",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Boadicee",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "GAGARIN",
    "source": "Rise of the Ancients event",
    "chestNumber": 5
  },
  {
    "from": "Cliffhanger",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Ollo II",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Z",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "MII Mighty Micho",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Rob",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Sir Dori",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Lirosin",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "TheLeo",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Athena",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Nejinn IV",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Cewyn",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Keleve",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Babei",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Karl Killer",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Domina",
    "source": "Rise of the Ancients event",
    "chestNumber": 4
  },
  {
    "from": "Gardashura",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "kimo",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Kizil Elma",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Ballage",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Nerdanilas",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Bardin",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "nomad",
    "source": "Epic Ancient squad",
    "chestNumber": 247
  },
  {
    "from": "MBAH IV",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Marauders",
    "source": "Rise of the Ancients event",
    "chestNumber": 4
  },
  {
    "from": "Auth",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "poops",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Kelerus",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Falcon Eye",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Carlos Rengoku",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "SmokinLauren?",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Metilar",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Ares",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "MBAH IV",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Babei",
    "source": "Level 25 Crypt",
    "chestNumber": 3
  },
  {
    "from": "Jedi Tano",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Rob",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Keleve",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Brakus",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Keleve",
    "source": "Level 35 epic Crypt",
    "chestNumber": 6
  },
  {
    "from": "Mag junior",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Gromuro them Babies",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Kabandis",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Sashott",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Onurb",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Grimsborith Orik",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Rasses74",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "TH R YLOSII",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Morana",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Emil SK 1",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "sk",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Grande Inverno",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Fobor",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Supergiri",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Tojakora",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "viking sv",
    "source": "Rise of the Ancients event",
    "chestNumber": 4
  },
  {
    "from": "Matija Gubec",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Kizil Elma",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Leonidas",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Nejinn IV",
    "source": "Epic Ancient squad",
    "chestNumber": 256
  },
  {
    "from": "Ollo II",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Tygojind",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Badur",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Marond",
    "source": "Level 30 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Ilvenen",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Marond",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Marond",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Henry",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Marond",
    "source": "Level 25 Crypt",
    "chestNumber": 6
  },
  {
    "from": "Cewyn",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Eyanin",
    "source": "Bank",
    "chestNumber": 3
  },
  {
    "from": "Kizil Elma",
    "source": "Bank",
    "chestNumber": 3
  },
  {
    "from": "Lirosin",
    "source": "Bank",
    "chestNumber": 9
  },
  {
    "from": "Badur",
    "source": "Level 25 Crypt",
    "chestNumber": 12
  },
  {
    "from": "Matija Gubec",
    "source": "Level 25 Crypt",
    "chestNumber": 4
  },
  {
    "from": "Matija Gubec",
    "source": "Level 35 epic Crypt",
    "chestNumber": 8
  },
  {
    "from": "Athena",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "BiG G",
    "source": "Level 15 Crypt",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 10 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 25 Crypt",
    "chestNumber": 11
  },
  {
    "from": "Emil SK 1",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "BiG G",
    "source": "Level 5 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Badur",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Cewyn",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Brakus",
    "source": "Arena",
    "chestNumber": 1
  },
  {
    "from": "sk",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 Crypt",
    "chestNumber": 8
  },
  {
    "from": "Marauders",
    "source": "Level 30 Citadel",
    "chestNumber": 7
  },
  {
    "from": "Brakus",
    "source": "Level 25 Crypt",
    "chestNumber": 15
  },
  {
    "from": "Jurandowna",
    "source": "Level 25 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Brakus",
    "source": "Union of Triumph personal reward",
    "chestNumber": 3
  },
  {
    "from": "Kelerus",
    "source": "Level 20 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Jurandowna",
    "source": "Level 30 rare Crypt",
    "chestNumber": 6
  },
  {
    "from": "TheLeo",
    "source": "Level 20 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Sir Dori",
    "source": "Level 25 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Kelerus",
    "source": "Level 30 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Brakus",
    "source": "Level 25 epic Crypt",
    "chestNumber": 10
  },
  {
    "from": "Kabandis",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Kabandis",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Kabandis",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Brakus",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Amginad",
    "source": "Level 25 Crypt",
    "chestNumber": 1
  },
  {
    "from": "Marond",
    "source": "Level 35 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 30 rare Crypt",
    "chestNumber": 5
  },
  {
    "from": "Hikmet Kocer13",
    "source": "Level 30 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Tojakora",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Lirosin",
    "source": "Level 25 Crypt",
    "chestNumber": 20
  },
  {
    "from": "Redman",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Keleve",
    "source": "Mercenary Exchange",
    "chestNumber": 2
  },
  {
    "from": "Nerneen",
    "source": "Level 25 epic Crypt",
    "chestNumber": 28
  },
  {
    "from": "Gromuro them Babies",
    "source": "Clan wealth",
    "chestNumber": 5
  },
  {
    "from": "Lirosin",
    "source": "Level 30 Citadel",
    "chestNumber": 4
  },
  {
    "from": "Nerneen",
    "source": "Level 30 epic Crypt",
    "chestNumber": 1
  },
  {
    "from": "Lirosin",
    "source": "Level 30 rare Crypt",
    "chestNumber": 3
  },
  {
    "from": "Lirosin",
    "source": "Level 30 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "wil",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Eyanin",
    "source": "Rise of the Ancients event",
    "chestNumber": 13
  },
  {
    "from": "Eyanin",
    "source": "Level 25 Crypt",
    "chestNumber": 14
  },
  {
    "from": "Eyanin",
    "source": "Level 25 Citadel",
    "chestNumber": 1
  },
  {
    "from": "Eyanin",
    "source": "Level 25 epic Crypt",
    "chestNumber": 2
  },
  {
    "from": "Eyanin",
    "source": "Level 25 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Falcon Eye",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Athena",
    "source": "Level 25 epic Crypt",
    "chestNumber": 5
  },
  {
    "from": "Fallegin",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 rare Crypt",
    "chestNumber": 2
  },
  {
    "from": "Rainbrand",
    "source": "Level 30 rare Crypt",
    "chestNumber": 1
  },
  {
    "from": "Grande Inverno",
    "source": "Mercenary Exchange",
    "chestNumber": 1
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 Crypt",
    "chestNumber": 12
  },
  {
    "from": "Rainbrand",
    "source": "Level 25 epic Crypt",
    "chestNumber": 3
  },
  {
    "from": "Gardashura",
    "source": "Level 25 Crypt",
    "chestNumber": 8
  }
];
